/*¿Cuánto tuvo que pagar la consulta el paciente con el turno nro 146?
Teniendo en cuenta que el paciente debe pagar el costo de la consulta del médico menos lo que cubre la cobertura de la obra social. 
La cobertura de la obra social está expresado en un valor decimal entre 0 y 1. Siendo 0 el 0% de cobertura y 1 el 100% de la cobertura.
*/
SELECT MED.COSTO_CONSULTA- (MED.COSTO_CONSULTA*OS.COBERTURA) AS TOTAL, MED.COSTO_CONSULTA,OS.COBERTURA
FROM MEDICOS AS MED
INNER JOIN TURNOS AS T ON T.IDMEDICO= MED.IDMEDICO
INNER JOIN PACIENTES AS P ON P.IDPACIENTE= T.IDPACIENTE
INNER JOIN OBRAS_SOCIALES AS OS ON OS.IDOBRASOCIAL= P.IDOBRASOCIAL
WHERE T.IDTURNO= 146

SELECT * FROM TURNOS AS TUR 
INNER JOIN MEDICOS AS MED ON MED.IDMEDICO= TUR.IDMEDICO
WHERE TUR.IDTURNO=146
 
 SELECT * FROM OBRAS_SOCIALES AS OS
 INNER JOIN PACIENTES AS PAC ON PAC.IDOBRASOCIAL= OS.IDOBRASOCIAL
 WHERE PAC.IDPACIENTE=79
/*¿Qué Obras Sociales cubren a pacientes que se hayan atendido en algún turno con algún médico de especialidad 'Odontología'?*/

SELECT OS.NOMBRE FROM OBRAS_SOCIALES AS OS WHERE OS.IDOBRASOCIAL IN(
SELECT PAC.IDOBRASOCIAL FROM PACIENTES AS PAC
INNER JOIN TURNOS AS TUR ON TUR.IDPACIENTE=PAC.IDPACIENTE
INNER JOIN MEDICOS AS MED ON MED.IDMEDICO= TUR.IDMEDICO
INNER JOIN ESPECIALIDADES AS ESP ON ESP.IDESPECIALIDAD= MED.IDESPECIALIDAD
WHERE ESP.NOMBRE= 'Odontología'
)


--¿Cuál es el costo de la consulta promedio de cualquier especialista en "Oftalmología"?

SELECT AVG(MED.COSTO_CONSULTA*1.0) AS PROMEDIO  FROM  MEDICOS AS MED
INNER JOIN ESPECIALIDADES AS ESP ON ESP.IDESPECIALIDAD= MED.IDESPECIALIDAD
WHERE ESP.NOMBRE='OFTALMOLOGÍA'

SELECT * FROM MEDICOS  AS MED
INNER JOIN ESPECIALIDADES AS ESP ON ESP.IDESPECIALIDAD= MED.IDESPECIALIDAD
WHERE ESP.NOMBRE='OFTALMOLOGÍA'

--¿Cuántos médicos tienen la especialidad "Gastroenterología" ó "Pediatría"?
SELECT  COUNT( DISTINCT  MED.IDMEDICO) FROM MEDICOS AS MED
INNER JOIN ESPECIALIDADES AS ES ON ES.IDESPECIALIDAD= MED.IDESPECIALIDAD
WHERE ES.NOMBRE='Pediatría' OR ES.NOMBRE='Gastroenterología' 


--¿Cuál es la cantidad de pacientes que no se atendieron en el año 2015?
 SELECT  COUNT( DISTINCT TUR.IDPACIENTE) FROM PACIENTES AS PAC 
 INNER JOIN TURNOS AS TUR ON TUR.IDPACIENTE=PAC.IDPACIENTE
 WHERE YEAR(TUR.FECHAHORA) <> 2015

 SELECT  COUNT( DISTINCT PAC.IDPACIENTE) FROM PACIENTES AS PAC  WHERE PAC.IDPACIENTE NOT IN(
 SELECT TUR.IDPACIENTE FROM TURNOS AS TUR
 INNER JOIN PACIENTES AS P ON P.IDPACIENTE= TUR.IDPACIENTE
 WHERE YEAR(TUR.FECHAHORA) = 2015
 )
 --¿Cuántos pacientes distintos se atendieron en turnos que duraron más que la duración promedio?
 SELECT COUNT(DISTINCT TUR.IDPACIENTE) AS TOTAL FROM  TURNOS AS TUR WHERE TUR.DURACION> (
 SELECT AVG(DURACION *1.0) FROM TURNOS
 )
 --¿Cuántas médicas cobran sus honorarios de consulta un costo mayor a $1000?

 SELECT COUNT(DISTINCT MED.IDMEDICO) FROM MEDICOS AS MED
  WHERE MED.SEXO='F' AND MED.COSTO_CONSULTA>1000

--  ¿Cuál es el apellido del médico (sexo masculino) con más antigüedad de la clínica?

SELECT TOP 10 * FROM MEDICOS AS MED
WHERE MED.SEXO='M'
ORDER BY MED.FECHAINGRESO ASC


--¿Cuántos turnos fueron atendidos por la doctora Flavia Rice?
SELECT COUNT( TUR.IDMEDICO) FROM MEDICOS AS MED
INNER JOIN TURNOS AS TUR ON TUR.IDMEDICO= MED.IDMEDICO
WHERE MED.APELLIDO='RICE ' AND MED.NOMBRE='FLAVIA'

--¿Cuáles son el/los paciente/s que se atendieron más veces? (indistintamente del sexo del paciente)
SELECT PAC.IDPACIENTE, PAC.APELLIDO,PAC.NOMBRE , COUNT(PAC.IDPACIENTE) 'TOTAL' FROM TURNOS AS TUR
INNER JOIN PACIENTES AS PAC ON PAC.IDPACIENTE= TUR.IDPACIENTE
GROUP BY PAC.IDPACIENTE, PAC.APELLIDO,PAC.NOMBRE 
ORDER BY COUNT(PAC.IDPACIENTE) DESC