
--CREACION DE VISTA
CREATE VIEW VW_LISTADOENVIOS AS
SELECT CLI.Nombres,CLI.Apellidos,PED.Costo,ENV.Direccion  FROM Clientes AS CLI
INNER JOIN Pedidos AS PED ON PED.IDCliente= CLI.ID
INNER JOIN Envios AS ENV ON ENV.IDPedido= PED.ID

--SELECT DE VISTA ORIGINAL
SELECT * FROM VW_LISTADOENVIOS
WHERE Costo> 20000

--MODIFICACION DE UNA VISTA YA EXISTENTE , FUNCION ALTER
-- SE MUESTRA EN EL LISTADO LOCALIDAD Y PROVINCIA
--SE JOINEA CON DOS TALA MAS (LOCALIDAD/PROVINCIA)
ALTER VIEW VW_LISTADOENVIOS AS
SELECT CLI.Nombres,CLI.Apellidos,PED.Costo,ENV.Direccion,LOC.Nombre AS 'LOCALIDAD',PROV.Nombre AS 'PROVINCIA'
FROM Clientes AS CLI
INNER JOIN Pedidos AS PED ON PED.IDCliente= CLI.ID
INNER JOIN Envios AS ENV ON ENV.IDPedido= PED.ID
INNER JOIN Localidades AS LOC ON LOC.ID= ENV.IDLocalidad
INNER JOIN Provincias AS PROV ON PROV.ID= LOC.IDProvincia


--ELIMINA EL OBJETO VISTA
DROP VIEW VW_LISTADOENVIOS